// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZK0hUEcLYDEeEv3lHde14W73HdNjJOsw',
    appId: '1:507663082989:web:5d77efb991ad96a1e633e4',
    messagingSenderId: '507663082989',
    projectId: 'crud-app-a1406',
    authDomain: 'crud-app-a1406.firebaseapp.com',
    storageBucket: 'crud-app-a1406.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCre0zum1azDnzu917Li-PkIwoFf5eGpMA',
    appId: '1:507663082989:android:0e57119c2b7c32b5e633e4',
    messagingSenderId: '507663082989',
    projectId: 'crud-app-a1406',
    storageBucket: 'crud-app-a1406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7vjFjfeABq6dzWO9NoJSdg59ilQooeRE',
    appId: '1:507663082989:ios:89126f9edb17b2f1e633e4',
    messagingSenderId: '507663082989',
    projectId: 'crud-app-a1406',
    storageBucket: 'crud-app-a1406.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7vjFjfeABq6dzWO9NoJSdg59ilQooeRE',
    appId: '1:507663082989:ios:be564bafd86d4559e633e4',
    messagingSenderId: '507663082989',
    projectId: 'crud-app-a1406',
    storageBucket: 'crud-app-a1406.appspot.com',
    iosBundleId: 'com.example.crudApp.RunnerTests',
  );
}
